added and modified some additional workflow actions

diff --git a/.github/workflows/action_ci.yml b/.github/workflows/action_ci.yml
--- a/.github/workflows/action_ci.yml
+++ b/.github/workflows/action_ci.yml
@@ -46,14 +46,37 @@ jobs:
         run: |
           dotnet publish -c "${{ env.CONFIGURATION }}" -f "${{ env.NET_CORE_VERSION }}" -o "out/generic" -p:LinkDuringPublish=false --nologo
 
-      - name: Upload ASF_ItemDropper
+      - name: Publish ASF_ItemDropper for .NET Framework
+        run: |
+          dotnet publish -c "${{ env.CONFIGURATION }}" -f "${{ env.NET_FRAMEWORK_VERSION }}" -o "out/generic-netf" -p:LinkDuringPublish=false --nologo
+
+      - name: Show build environment
+        shell: sh
+        run: |
+          set -eu
+
+          pwd
+          ls -la
+
+      - name: Upload ASF_ItemDropper generic artifacts
         uses: actions/upload-artifact@v2
         with:
           # Artifact name
-          name: ASF_ItemDropper
+          name: ${{ github.event.repository.name }}-generic
           # Destination path(s)
           path: |
             out/generic/ASFItemDropper.*
+            idropdeflist.txt
+          if-no-files-found: warn # 'error', 'warn' or 'ignore' are also available, defaults to `warn`
+
+      - name: Upload ASF_ItemDropper generic-netf artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          # Artifact name
+          name: ${{ github.event.repository.name }}-generic-netf
+          # Destination path(s)
+          path: |
+            out/generic-netf/ASFItemDropper.*
             idropdeflist.txt
           if-no-files-found: warn # 'error', 'warn' or 'ignore' are also available, defaults to `warn`
 
